# Generated by Django 2.1 on 2018-10-07 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0002_auto_20181006_0622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('who', 'whom')},
        ),
    ]
