# Generated by Django 2.1 on 2018-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0003_auto_20181007_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
